version: "3.9"

services:
  db:
    image: postgres:15
    container_name: bunyodkor_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bunyodkor_net

  web:
    build: .
    container_name: web                   # ðŸ‘ˆ MUHIM: nomi "web" boâ€˜lishi kerak
    command: uvicorn main:app --host 0.0.0.0 --port 8008
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bunyodkor_net

  nginx:
    image: nginx:latest
    container_name: bunyodkor_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/bunyodkor.api.cims.cognilabs.org/:/etc/letsencrypt/live/bunyodkor.api.cims.cognilabs.org/:ro
      - /etc/letsencrypt/archive/bunyodkor.api.cims.cognilabs.org/:/etc/letsencrypt/archive/bunyodkor.api.cims.cognilabs.org/:ro
    depends_on:
      - web
    networks:
      - bunyodkor_net

volumes:
  postgres_data:

networks:
  bunyodkor_net:
    driver: bridge

