version: "3.9"

services:
  db:
    image: postgres:15
    container_name: bunyodkor_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2222
      POSTGRES_DB: newbunyodkor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bunyodkor_net

  web:
    build: .
    container_name: bunyodkor_api
    command: uvicorn main:app --host 0.0.0.0 --port 8008
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bunyodkor_net

  nginx:
    image: nginx:latest
    container_name: bunyodkor_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - web
    networks:
      - bunyodkor_net

volumes:
  postgres_data:

networks:
  bunyodkor_net:
