name: Deploy to fixed directory

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [ self-hosted, prod ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync code to production directory
        run: |
          rsync -av --delete \
            $GITHUB_WORKSPACE/ \
            /workplace/bunyodkor/

      - name: Deploy with Docker Compose
        working-directory: /workplace/bunyodkor
        run: |
          docker compose down
          docker compose up -d --build
